[build]
  command = "DISABLE_ESLINT_PLUGIN=true NEXT_DISABLE_ESLINT=1 npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NETLIFY_USE_PYTHON = "false"
  NEXT_DISABLE_ESLINT = "1"
  DISABLE_ESLINT_PLUGIN = "true"

# Redirects and headers are NGINX-style redirects and headers
# For more information see https://docs.netlify.com/routing/redirects/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
