[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_PYTHON = "false"

# Redirects for Next.js with Netlify runtime
# For more information see https://docs.netlify.com/routing/redirects/

# These redirects are handled by Next.js, but we can add Netlify-specific ones here if needed

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Note: Security headers are handled by Next.js config for better compatibility
