[build]
  command = "npm ci && npm run build"

# Force cache invalidation
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_PYTHON = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redirects for Next.js with Netlify runtime
# For more information see https://docs.netlify.com/routing/redirects/

# These redirects are handled by Next.js, but we can add Netlify-specific ones here if needed

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Note: Security headers are handled by Next.js config for better compatibility
